In [1]:
import pandas as pd

In [7]:
df = pd.read_csv("explosive_media_messages.csv")

In [10]:
df.head(5)

,message_text_persian,message_text_english,time_est,date,has_media,media_filename,audio_transcription_persian,audio_transcription_persian_v2,audio_transcription_english,ocr_text_persian,ocr_text_english,keywords,screenshots,theme,include_person,AI_generated
0,صبحتون بخیر 👋😁 \n\n🆔 @akhbarenfejari,Good morning 👋😁,2025-12-31 22:58:12 EST,2025-12-31,Y,2025-12-31_001.mp4,I'm...,بایدیدیدیدیدیدیدیدیدیدیدیدیدیدیدیدیدیدیدیدیدید...,[Unintelligible repetition],NaN,NaN,"greeting, morning",NaN,Pop culture,NaN,No
1,چی میخواستیم، چی شد!!!😣\n\n🔺️معاون سیاسی استان...,"What we wanted, what happened!!! 😣 The politic...",2025-12-31 23:46:46 EST,2025-12-31,Y,2025-12-31_002.jpg,NaN,NaN,NaN,امیرحسام خدایاریفرد\nمتولد ۱۳۸۲ - شهادت در کوه...,Amir Hossam Khodayari Fard\nBorn 1382 - Martyr...,"Kuhdasht, Lorestan, martyr, police, Basij, unr...",NaN,Protests,NaN,No
2,🛑 سرما امروز میره، فردا برمی‌گرده\n\n🌨امروز تو...,"🛑 Cold is leaving today, coming back tomorrow....",2026-01-01 00:00:20 EST,2026-01-01,Y,2026-01-01_001.jpg,NaN,NaN,NaN,درای خزر\nدریای عمان\nخلیج فارس,Caspian Sea\nSea of Oman\nPersian Gulf,"snow, cold weather, West Azerbaijan, Zagros, f...",NaN,Weather and landscape,NaN,No
3,🛑 مطالبه آره، بازی تو زمین دشمن نه\n\n🔺️دکتر ر...,"🛑 Demands yes, playing on enemy territory no. ...",2026-01-01 00:13:22 EST,2026-01-01,Y,2026-01-01_002.mp4,این نوخد بسیار بسیار حصاسی چا توش مانان ایرندر...,این نقطه بسیار-بسیار حساسه چون دشمنان ایران در...,[Heavily garbled transcription - unable to ext...,NaN,NaN,"foreign interference, Israel, Reza Pahlavi, pr...",NaN,Foreign intervention,"Ramin Kamran, Reza Pahlavi",No
4,🛑 حمله آمریکا به ۳ قایق دیگه\n\n💣 آمریکا دوبار...,🛑 America attacks 3 more boats. America again ...,2026-01-01 00:20:49 EST,2026-01-01,Y,2026-01-01_003.mp4,you you,NaN,NaN,NaN,NaN,"US military, boats, international waters, atta...",NaN,War coverage,NaN,No

In [19]:
df['date'] = pd.to_datetime(df['date'])                                                                                                                   
                                                                                                                                                                      
# Just Jan 1, 2026 (one specific day)                                                                                                                               
jan1 = df[df['date'].dt.date == pd.Timestamp('2026-01-01').date()]        

jan1.sort_values("time_est")

,message_text_persian,message_text_english,time_est,date,has_media,media_filename,audio_transcription_persian,audio_transcription_persian_v2,audio_transcription_english,ocr_text_persian,ocr_text_english,keywords,screenshots,theme,include_person,AI_generated
2,🛑 سرما امروز میره، فردا برمی‌گرده\n\n🌨امروز تو...,"🛑 Cold is leaving today, coming back tomorrow....",2026-01-01 00:00:20 EST,2026-01-01,Y,2026-01-01_001.jpg,NaN,NaN,NaN,درای خزر\nدریای عمان\nخلیج فارس,Caspian Sea\nSea of Oman\nPersian Gulf,"snow, cold weather, West Azerbaijan, Zagros, f...",NaN,Weather and landscape,NaN,No
3,🛑 مطالبه آره، بازی تو زمین دشمن نه\n\n🔺️دکتر ر...,"🛑 Demands yes, playing on enemy territory no. ...",2026-01-01 00:13:22 EST,2026-01-01,Y,2026-01-01_002.mp4,این نوخد بسیار بسیار حصاسی چا توش مانان ایرندر...,این نقطه بسیار-بسیار حساسه چون دشمنان ایران در...,[Heavily garbled transcription - unable to ext...,NaN,NaN,"foreign interference, Israel, Reza Pahlavi, pr...",NaN,Foreign intervention,"Ramin Kamran, Reza Pahlavi",No
4,🛑 حمله آمریکا به ۳ قایق دیگه\n\n💣 آمریکا دوبار...,🛑 America attacks 3 more boats. America again ...,2026-01-01 00:20:49 EST,2026-01-01,Y,2026-01-01_003.mp4,you you,NaN,NaN,NaN,NaN,"US military, boats, international waters, atta...",NaN,War coverage,NaN,No
5,🛑 فیلم‌های سینمایی امروز تلویزیون \n\n🔹«کد ۸» ...,🛑 Today's cinema films on television. [Film li...,2026-01-01 00:23:37 EST,2026-01-01,Y,2026-01-01_004.jpg,NaN,NaN,NaN,NaN,NaN,"cinema, television, films, entertainment, sche...",NaN,Pop culture,NaN,No
6,🛑 آقایون، به اعتراض تو چهارچوب بها بدید!!\n\n🔺...,"🛑 Gentlemen, give value to protests within a f...",2026-01-01 00:39:57 EST,2026-01-01,Y,2026-01-01_005.mp4,اگه ایتراز در چا هرچو بها بیتیت هر جا ان انت ا...,آگایون بی ایتراز در چاارچو بها بیتیت. هر جا ان...,"Gentlemen, protest within a framework has valu...",NaN,NaN,"protests, economic issues, civil unrest, Irani...",NaN,Protests,Amin Salimi,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64,🏆 بارسا برنده جایزه بهترین تیم اروپایی سال شد\...,🏆 Barcelona became the winner of the best Euro...,2026-01-01 13:38:49 EST,2026-01-01,Y,2026-01-01_062.jpg,NaN,NaN,NaN,NaN,NaN,"Barcelona, European award, football, Flick",NaN,Sports,NaN,No
65,تیک‌تاک، پادشاه جدید اخبار!😲\n\n💻 تیک‌تاک با س...,"TikTok, the new king of news!😲\n\n💻 TikTok, su...",2026-01-01 13:53:25 EST,2026-01-01,Y,2026-01-01_063.jpg,NaN,NaN,NaN,NaN,NaN,"TikTok, news source, social media, American youth",NaN,Pop culture,NaN,No
66,حققققققققققق 😭😁\n\nصبحتون بخیر 👋,Hahahaha 😭😁\n\nGood morning 👋,2026-01-01 23:28:10 EST,2026-01-01,Y,2026-01-01_064.mp4,Only you,آروییییییییییییییییییییییییییییییییییییییییییی...,Ohhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh...,NaN,NaN,"greeting, casual content",NaN,Pop culture,NaN,No
67,🏞 **تالاب سانتاروزا؛ دریاچه‌ای سرخ رنگ وسط بیا...,🏞 **Santa Rosa Wetland; a red-colored lake in ...,2026-01-01 23:40:14 EST,2026-01-01,Y,2026-01-01_065.mp4,Music,NaN,NaN,NaN,NaN,"Chile, desert, red lake, geography",NaN,Weather and landscape,NaN,No
68,🛑 فیلم‌های سینمایی امروز تلویزیون\n\n🔹«تعطیلات...,"🛑 Today's cinema movies on television\n\n🔹""8-B...",2026-01-01 23:49:51 EST,2026-01-01,Y,2026-01-01_066.jpg,NaN,NaN,NaN,NaN,NaN,"cinema, television, movies, schedule",NaN,Pop culture,NaN,No

In [ ]:
jan1[jan1["message_text_english"].str.contains('christmas', case=False, na=False)]

,message_text_persian,message_text_english,time_est,date,has_media,media_filename,audio_transcription_persian,audio_transcription_persian_v2,audio_transcription_english,ocr_text_persian,ocr_text_english,keywords,screenshots,theme,include_person,AI_generated
9,سال نوی میلادی رو به همه هموطنای مسیحیمون تبری...,We congratulate all our Christian compatriots ...,2026-01-01 01:05:44 EST,2026-01-01,N,NaN,NaN,NaN,NaN,NaN,NaN,"AI, Christmas, VPN, Google Gemini, sanctions",NaN,Using AI,NaN,Yes

In [ ]:

jan1[jan1['date'].dt.date == pd.Timestamp('2026-01-09').date()]

Empty DataFrame
Columns: [message_text_persian, message_text_english, time_est, date, has_media, media_filename, audio_transcription_persian, audio_transcription_persian_v2, audio_transcription_english, ocr_text_persian, ocr_text_english, keywords, screenshots, theme, include_person, AI_generated]
Index: []

In [47]:
print("The theme breakdown:") 
df["theme"].value_counts()

The theme breakdown:

theme
War coverage             585
International news       396
Sports                   317
Weather and landscape    246
Foreign intervention     219
Pop culture              183
Iranian economy          180
Pro-regime               123
Gaza Genocide             98
Protests                  93
Anti-regime               85
Using AI                  84
Exams                     53
Religious content         49
Health                    42
LEGO                      40
Hamas                      4
Name: count, dtype: int64

In [ ]:
antiregime = df[df["theme"] == "Anti-regime"]
proregime = df[df["theme"] == "Pro-regime"]

for text in antiregime["message_text_english"].sample(10, random _state=42):                                                                                                            
      print(text)                                                                                                                                                     
      print("---")

🛑 Shooting at a member of parliament in Takestan

🔺️The personal vehicle of Abbas Bigdeli, representative of Takestan, was targeted by buckshot. In this assassination attempt, fortunately, no harm came to the parliament member.

🔺️Bigdeli is a member of the National Security and Foreign Policy Commission of parliament. Investigation into the dimensions and motives of this incident is being pursued by relevant authorities.

🆔 @akhbarenfejari
---
🛑 It's Parliament's fault. 🔺️ We had selected someone else for the Ministry of Jihad Agriculture. This same parliament told us that so-and-so is good for the ministry. 🔺️ We made our selection based on the parliament's agriculture committee's opinion. We set aside the person we had selected and I did not select the person you mention is my friend. 🆔 @akhbarenfejari
---
🛑 Either you were lying back then or now!

🥱 Over the past 8 months, Trump kept saying that Iran's nuclear industry was completely destroyed and he was able to set back Iran's capability to develop nuclear weapons for many years!

🧐 So the question is: were you lying back then or now?

🆔 @akhbarenfejari
---
They twisted some people's ears 😎

🔻 The economy minister said:
Managers who disobey currency supply to the market will be dismissed within one day.

🔻 Yesterday a manager was dismissed for this reason.

🆔 @akhbarenfejari
---
🛑 How unscrupulous you are

🔺️ Rioters in Mashhad set a motorcycle courier on fire.

⚠️ Many experts say that when Trump said if things turn violent he will come help rioters, he's actually giving a code for rioters to use more violence and execute that mass-killing project we mentioned before.
---
IRGC can take a break.
It's the Lurs' turn.

🆔 @ExplosiveMedia
---
🛑 What was he doing?

🚓 Police said:
We impounded a passenger vehicle that had over 1.2 billion tomans in traffic violations.

🆔 @akhbarenfejari
---
🛑 Only Those 17 Thousand Who Liked It

🔺️They released a film called a plainclothes officer's confrontation with a protester.

🔺️Neither that man is a plainclothes officer nor that woman is a protester! The film is from 7 months ago and is related to a family dispute in Khuzestan.

🆔 @akhbarenfejari
---
🛑 Misuse of old films again!

📱 Manoto aired an old video from four years ago as last night's protests in Zarindasht!!!

🆔 @akhbarenfejari
---
🛑 The knife doesn't cut its own handle

🔺️ An American media activist said our government is so corrupted and rotten that even the name of the president (Trump) has appeared more than 38 thousand times in Epstein documents.

🔺 The US government is protecting child abusers; because they themselves are those child abusers!

🆔 @akhbarenfejari
---

In [60]:
proregime.head(5)

,message_text_persian,message_text_english,time_est,date,has_media,media_filename,audio_transcription_persian,audio_transcription_persian_v2,audio_transcription_english,ocr_text_persian,ocr_text_english,keywords,screenshots,theme,include_person,AI_generated
17,💡 انتقاد رئیس جمهور از اسراف برق و گاز در محل ...,💡 The president's criticism of wasting electri...,2026-01-01 03:07:27 EST,2026-01-01,Y,2026-01-01_015.mp4,آلا میمادیم چرگا هاییاتوشم آ روشن بود شب جایک ...,آلام میمدیم چره هایه هایه تشمه روشن بود. شبجای...,We come to why the lights were on. I should ha...,NaN,NaN,"president, electricity, gas, conservation, Sha...",NaN,Pro-regime,NaN,No
97,✊️ مسیر گلزار شهدای کرمان، به سمت مزار حاج قاس...,✊️ The path of the Martyrs' Cemetery in Kerman...,2026-01-02 07:08:00 EST,2026-01-02,Y,2026-01-02_029.mp4,גרח נחווד רוב,جاه نخوض را بایدیم,We had to leave them,NaN,NaN,"Hajj Qassem, martyrs, shrine, Kerman, pilgrimage",NaN,Pro-regime,NaN,No
110,لحظه دريافت سیگنال از ماهواره‌ ایرانی کوثر و ش...,The moment of receiving the signal from the Ir...,2026-01-02 10:14:44 EST,2026-01-02,Y,2026-01-02_042.mp4,Man kann hier doch nur ein bisschen mehr. Scho...,دیستیست مدنیدیدیدیدیدیدیدیدیدیدیدیدیدیدیدیدیدی...,This is a... this is a... this is a...,NaN,NaN,"Kavoshgar satellite, Iranian space program, na...",NaN,Pro-regime,NaN,No
128,🛑 امیدواریم!\n\nرئیس‌جمهور گفته: \nلازم باشه خ...,🛑 We hope!\n\nThe president said:\nIf necessar...,2026-01-02 13:33:49 EST,2026-01-02,Y,2026-01-02_060.mp4,از نسیم اصنع فمو مشکل پیدا کنه و احتى این ای ر...,آزنیسی مصنفا مومشکل پیدا کنه. وحته این آی رو ک...,We find it difficult. And when you hear this t...,NaN,NaN,"president, guilds, economic issues, dialogue",NaN,Pro-regime,NaN,No
155,یه بسیجی دیگه هم شهید شد 🖤\n\n🔺️یه تیم ۶ نفره‌...,Another Basiji was martyred 🖤\n\n🔺️An armed te...,2026-01-03 03:29:24 EST,2026-01-03,Y,2026-01-03_014.jpg,NaN,NaN,NaN,NaN,NaN,"Basij, martyrdom, armed attack, Kerman, resist...",NaN,Pro-regime,Ali Azizi,No

In [73]:
firstset = df[df["date"].between("2025-12-31", "2026-02-28")] 
firstset["theme"].value_counts()

theme
War coverage             518
International news       394
Sports                   317
Weather and landscape    245
Foreign intervention     215
Pop culture              176
Iranian economy          175
Pro-regime               105
Gaza Genocide             97
Protests                  86
Using AI                  84
Anti-regime               79
Exams                     53
Health                    41
Religious content         37
LEGO                      26
Hamas                      4
Name: count, dtype: int64

In [81]:
secondset = df[df["date"].between("2026-02-28", "2026-04-09")]
secondset = secondset[secondset["theme"] == "Anti-regime"]

secondset

,message_text_persian,message_text_english,time_est,date,has_media,media_filename,audio_transcription_persian,audio_transcription_persian_v2,audio_transcription_english,ocr_text_persian,ocr_text_english,keywords,screenshots,theme,include_person,AI_generated
2732,**کاش اونو نمیگفتی!!🥴😩\n**\n♨️ از‌صحبت های پرح...,**I wish you hadn't said that!!🥴😩\n**\n♨️ From...,2026-03-14 12:06:27 EDT,2026-03-14,Y,2026-03-14_039.mp4,بسپار جمجوم رابر حقس باهی ورحقس باهی ورحقس باه...,[music or noise - no clear speech],[This segment is heavily corrupted with repeti...,NaN,NaN,"separatist groups, western unrest, political c...",NaN,Anti-regime,NaN,No
2773,**قانون آدما نیست که، قانون جنگله!!🐗🐯**\n\n♨️ ...,"**Laws aren't for people, laws are for the jun...",2026-03-14 13:01:10 EDT,2026-03-14,Y,2026-03-14_080.mp4,I'm not a good guy. 1.0-2.0-2.0-2.0-2.0-2.0-2...,[no speech detected],This segment contains only repetitive phrases ...,NaN,NaN,"law, justice system, international law, govern...",NaN,Anti-regime,NaN,Yes
2824,The veil is thinning.\nGood. Evil.\n\nTime is ...,The veil is thinning.\nGood. Evil.\n\nTime is ...,2026-04-01 20:47:46 EDT,2026-04-01,Y,2026-04-01_002.mp4,De wacht is de zonje van de energie. De wacht ...,[music or noise - no clear speech],He raised the people he raised the people he r...,NaN,NaN,"resistance, uprising, revolution, propaganda",NaN,Anti-regime,NaN,Yes
2828,IRGC can take a break.\nIt’s the Lurs’ turn.\n...,IRGC can take a break.\nIt's the Lurs' turn.\n...,2026-04-03 09:42:21 EDT,2026-04-03,Y,NaN,NaN,NaN,NaN,NaN,NaN,"IRGC, military, satire, ethnic humor",NaN,Anti-regime,NaN,Yes
2833,The song used in the video.\n\nRise Up\nBy Meh...,The song used in the video. Rise Up By Mehdi R...,2026-04-06 20:46:25 EDT,2026-04-06,Y,NaN,NaN,NaN,NaN,NaN,NaN,"music, resistance, song, uprising",NaN,Anti-regime,Mehdi Rasouli,No
2834,One man. One tar. One homeland.\n\nIn honor of...,One man. One tar. One homeland. In honor of Al...,2026-04-07 11:45:27 EDT,2026-04-07,Y,NaN,NaN,NaN,NaN,NaN,NaN,"music, resistance, nationalism, patriotism, tar",NaN,Anti-regime,Ali Ghamsari,No